import type { Metadata } from "next";
import { locales } from "@/i18n/locales";
import { site } from "@/config/site";
import HotelScoreForm from "@/components/HotelScoreForm";

export function generateMetadata({ params }: { params: { locale: string } }): Metadata {
  const url = `/${params.locale}/for-hotels`;
  const languages = Object.fromEntries([
    ...locales.map((l) => [l, `/${l}/for-hotels`]),
    ["x-default", "/en/for-hotels"],
  ]);
  const title = `For hotels — get your cosy score | ${site.name}`;
  const description = "Hoteliers: submit your hotel and our AI scores it for cosiness — warmth, character, intimacy — with the signals it found.";
  return { title, description, alternates: { canonical: url, languages }, openGraph: { title, description, type: "website", url } };
}

export default function ForHotelsPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-10">
      <span className="inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1 rounded-full border" style={{ borderColor: "var(--line)", background: "var(--card)", color: "var(--ember-ink)" }}>
        For hotels
      </span>
      <h1 className="mt-4 font-display text-3xl md:text-4xl font-semibold tracking-tight">Get your hotel’s cosy score</h1>
      <p className="mt-3 max-w-2xl" style={{ color: "var(--muted)" }}>
        Submit your hotel and our AI runs it through the same cosiness scoring we use across the site —
        weighing property type and scale, amenities, the language of reviews, and setting. You’ll get a
        0–10 cosy score and the specific signals we detected.
      </p>
      <div className="mt-8">
        <HotelScoreForm />
      </div>
      <p className="mt-6 text-xs" style={{ color: "var(--muted)" }}>
        Scores are generated by AI from the details you provide. Richer, accurate input (website, real
        amenities, an honest description) yields a more confident score.
      </p>
    </div>
  );
}
